CREATE DATABASE EXP3;
USE EXP3;

-- Create Input Tables: Department and Employee.
CREATE TABLE Department (
	ID INT PRIMARY KEY, 
	DEPT_NAME VARCHAR(50)
);

CREATE TABLE Employee (
	ID INT,
	NAME VARCHAR(50),
	SALARY INT,
	DEPT_ID INT,
	FOREIGN KEY (DEPT_ID) REFERENCES Department(ID)
);

-- Populate the input data.
INSERT INTO Department (ID, DEPT_NAME) VALUES
(1, 'IT'),
(2, 'SALES');

INSERT INTO Employee (ID, NAME, SALARY, DEPT_ID) VALUES
(1, 'JOE', 70000, 1),
(2, 'JIM', 90000, 1),
(3, 'HENRY', 80000, 2),
(4, 'SAM', 60000, 2),
(5, 'MAX', 90000, 1);

-- Find the top earner in each department.
SELECT
	D.DEPT_NAME, E.NAME, E.SALARY
FROM
	EMPLOYEE AS E
INNER JOIN
	DEPARTMENT AS D
ON
	D.ID = E.DEPT_ID
WHERE
	E.SALARY
IN (
	SELECT MAX(E2.SALARY)
	FROM EMPLOYEE AS E2
	WHERE E2.DEPT_ID = E.DEPT_ID
)
ORDER BY
	D.DEPT_NAME;
